INSERT INTO `resources` (`id`,`key_name`,`display_name`,`created_at`,`updated_at`) VALUES (1,'profiles','profiles',NULL,NULL);
INSERT INTO `resources` (`id`,`key_name`,`display_name`,`created_at`,`updated_at`) VALUES (2,'profiles_create','profiles_create',NULL,NULL);
INSERT INTO `resources` (`id`,`key_name`,`display_name`,`created_at`,`updated_at`) VALUES (7,'profiles_edit','profiles_edit',NULL,NULL);
INSERT INTO `resources` (`id`,`key_name`,`display_name`,`created_at`,`updated_at`) VALUES (8,'profiles_view','profiles_view',NULL,NULL);
INSERT INTO `resources` (`id`,`key_name`,`display_name`,`created_at`,`updated_at`) VALUES (9,'profiles_enable','profiles_enable',NULL,NULL);
INSERT INTO `resources` (`id`,`key_name`,`display_name`,`created_at`,`updated_at`) VALUES (10,'profiles_remove','profiles_remove',NULL,NULL);
INSERT INTO `resources` (`id`,`key_name`,`display_name`,`created_at`,`updated_at`) VALUES (11,'privileges','privileges',NULL,NULL);
INSERT INTO `resources` (`id`,`key_name`,`display_name`,`created_at`,`updated_at`) VALUES (12,'privileges_create','privileges_create',NULL,NULL);
INSERT INTO `resources` (`id`,`key_name`,`display_name`,`created_at`,`updated_at`) VALUES (13,'privileges_view','privileges_view',NULL,NULL);
INSERT INTO `resources` (`id`,`key_name`,`display_name`,`created_at`,`updated_at`) VALUES (14,'privileges_remove','privileges_remove',NULL,NULL);
INSERT INTO `resources` (`id`,`key_name`,`display_name`,`created_at`,`updated_at`) VALUES (15,'roles','roles',NULL,NULL);
INSERT INTO `resources` (`id`,`key_name`,`display_name`,`created_at`,`updated_at`) VALUES (16,'roles_create','roles_create',NULL,NULL);
INSERT INTO `resources` (`id`,`key_name`,`display_name`,`created_at`,`updated_at`) VALUES (17,'roles_view','roles_view',NULL,NULL);
INSERT INTO `resources` (`id`,`key_name`,`display_name`,`created_at`,`updated_at`) VALUES (18,'roles_edit','roles_edit',NULL,NULL);
INSERT INTO `resources` (`id`,`key_name`,`display_name`,`created_at`,`updated_at`) VALUES (19,'roles_enable','roles_enable',NULL,NULL);
INSERT INTO `resources` (`id`,`key_name`,`display_name`,`created_at`,`updated_at`) VALUES (20,'roles_remove','roles_remove',NULL,NULL);
INSERT INTO `resources` (`id`,`key_name`,`display_name`,`created_at`,`updated_at`) VALUES (21,'profilesroles','profilesroles',NULL,NULL);
INSERT INTO `resources` (`id`,`key_name`,`display_name`,`created_at`,`updated_at`) VALUES (22,'profilesroles_create','profilesroles_create',NULL,NULL);
INSERT INTO `resources` (`id`,`key_name`,`display_name`,`created_at`,`updated_at`) VALUES (23,'profilesroles_view','profilesroles_view',NULL,NULL);
INSERT INTO `resources` (`id`,`key_name`,`display_name`,`created_at`,`updated_at`) VALUES (24,'profilesroles_remove','profilesroles_remove',NULL,NULL);
INSERT INTO `resources` (`id`,`key_name`,`display_name`,`created_at`,`updated_at`) VALUES (25,'security','Administrar Seguridad',NULL,NULL);
INSERT INTO `resources` (`id`,`key_name`,`display_name`,`created_at`,`updated_at`) VALUES (26,'users','Usuarios',NULL,NULL);
INSERT INTO `resources` (`id`,`key_name`,`display_name`,`created_at`,`updated_at`) VALUES (27,'users_create','Crear Usuarios',NULL,NULL);
INSERT INTO `resources` (`id`,`key_name`,`display_name`,`created_at`,`updated_at`) VALUES (28,'users_view','Mostrar Usuario',NULL,NULL);
INSERT INTO `resources` (`id`,`key_name`,`display_name`,`created_at`,`updated_at`) VALUES (29,'users_edit','Editar Usuario',NULL,NULL);
INSERT INTO `resources` (`id`,`key_name`,`display_name`,`created_at`,`updated_at`) VALUES (30,'users_enable','Habilitar/Deshabilitar Usuarios',NULL,NULL);
INSERT INTO `resources` (`id`,`key_name`,`display_name`,`created_at`,`updated_at`) VALUES (31,'users_remove','Eliminar Usuario',NULL,NULL);
INSERT INTO `resources` (`id`,`key_name`,`display_name`,`created_at`,`updated_at`) VALUES (32,'menuitems','Administrar menu items',NULL,NULL);
INSERT INTO `resources` (`id`,`key_name`,`display_name`,`created_at`,`updated_at`) VALUES (33,'menuitems_create','Crear menu item',NULL,NULL);
INSERT INTO `resources` (`id`,`key_name`,`display_name`,`created_at`,`updated_at`) VALUES (34,'menuitems_view','Ver menu item',NULL,NULL);
INSERT INTO `resources` (`id`,`key_name`,`display_name`,`created_at`,`updated_at`) VALUES (35,'menuitems_edit','Editar menu item',NULL,NULL);
INSERT INTO `resources` (`id`,`key_name`,`display_name`,`created_at`,`updated_at`) VALUES (36,'menuitems_remove','Eliminar menu item',NULL,NULL);
INSERT INTO `resources` (`id`,`key_name`,`display_name`,`created_at`,`updated_at`) VALUES (37,'modules','Administrar Módulos',NULL,NULL);
INSERT INTO `resources` (`id`,`key_name`,`display_name`,`created_at`,`updated_at`) VALUES (38,'modules_create','Crear Módulo',NULL,NULL);
INSERT INTO `resources` (`id`,`key_name`,`display_name`,`created_at`,`updated_at`) VALUES (39,'modules_view','Ver Módulo',NULL,NULL);
INSERT INTO `resources` (`id`,`key_name`,`display_name`,`created_at`,`updated_at`) VALUES (40,'modules_edit','Editar Módulo',NULL,NULL);
INSERT INTO `resources` (`id`,`key_name`,`display_name`,`created_at`,`updated_at`) VALUES (41,'modules_enable','Habilitar/Deshabilitar Módulo',NULL,NULL);
INSERT INTO `resources` (`id`,`key_name`,`display_name`,`created_at`,`updated_at`) VALUES (42,'modules_remove','Eliminar Módulo',NULL,NULL);
