INSERT INTO `privileges` (`id`,`role_id`,`resource_id`,`created_at`,`updated_at`) VALUES (9,1,2,'2018-04-30 02:22:15','2018-04-30 02:22:15');
INSERT INTO `privileges` (`id`,`role_id`,`resource_id`,`created_at`,`updated_at`) VALUES (11,1,1,'2018-04-30 03:26:38','2018-04-30 03:26:38');
INSERT INTO `privileges` (`id`,`role_id`,`resource_id`,`created_at`,`updated_at`) VALUES (12,1,11,NULL,NULL);
INSERT INTO `privileges` (`id`,`role_id`,`resource_id`,`created_at`,`updated_at`) VALUES (13,1,12,NULL,NULL);
INSERT INTO `privileges` (`id`,`role_id`,`resource_id`,`created_at`,`updated_at`) VALUES (14,1,13,NULL,NULL);
INSERT INTO `privileges` (`id`,`role_id`,`resource_id`,`created_at`,`updated_at`) VALUES (15,1,14,NULL,NULL);
INSERT INTO `privileges` (`id`,`role_id`,`resource_id`,`created_at`,`updated_at`) VALUES (16,1,7,'2018-04-30 03:45:22','2018-04-30 03:45:22');
INSERT INTO `privileges` (`id`,`role_id`,`resource_id`,`created_at`,`updated_at`) VALUES (17,1,9,'2018-04-30 03:45:31','2018-04-30 03:45:31');
INSERT INTO `privileges` (`id`,`role_id`,`resource_id`,`created_at`,`updated_at`) VALUES (18,1,10,'2018-04-30 03:45:50','2018-04-30 03:45:50');
INSERT INTO `privileges` (`id`,`role_id`,`resource_id`,`created_at`,`updated_at`) VALUES (19,1,8,'2018-04-30 03:45:58','2018-04-30 03:45:58');
INSERT INTO `privileges` (`id`,`role_id`,`resource_id`,`created_at`,`updated_at`) VALUES (20,1,15,NULL,NULL);
INSERT INTO `privileges` (`id`,`role_id`,`resource_id`,`created_at`,`updated_at`) VALUES (21,1,16,NULL,NULL);
INSERT INTO `privileges` (`id`,`role_id`,`resource_id`,`created_at`,`updated_at`) VALUES (22,1,17,NULL,NULL);
INSERT INTO `privileges` (`id`,`role_id`,`resource_id`,`created_at`,`updated_at`) VALUES (23,1,18,NULL,NULL);
INSERT INTO `privileges` (`id`,`role_id`,`resource_id`,`created_at`,`updated_at`) VALUES (24,1,19,NULL,NULL);
INSERT INTO `privileges` (`id`,`role_id`,`resource_id`,`created_at`,`updated_at`) VALUES (25,1,20,NULL,NULL);
INSERT INTO `privileges` (`id`,`role_id`,`resource_id`,`created_at`,`updated_at`) VALUES (26,1,21,NULL,NULL);
INSERT INTO `privileges` (`id`,`role_id`,`resource_id`,`created_at`,`updated_at`) VALUES (27,1,22,NULL,NULL);
INSERT INTO `privileges` (`id`,`role_id`,`resource_id`,`created_at`,`updated_at`) VALUES (28,1,23,NULL,NULL);
INSERT INTO `privileges` (`id`,`role_id`,`resource_id`,`created_at`,`updated_at`) VALUES (29,1,24,NULL,NULL);
INSERT INTO `privileges` (`id`,`role_id`,`resource_id`,`created_at`,`updated_at`) VALUES (30,1,25,NULL,NULL);
INSERT INTO `privileges` (`id`,`role_id`,`resource_id`,`created_at`,`updated_at`) VALUES (31,1,26,NULL,NULL);
INSERT INTO `privileges` (`id`,`role_id`,`resource_id`,`created_at`,`updated_at`) VALUES (32,1,27,NULL,NULL);
INSERT INTO `privileges` (`id`,`role_id`,`resource_id`,`created_at`,`updated_at`) VALUES (33,1,28,NULL,NULL);
INSERT INTO `privileges` (`id`,`role_id`,`resource_id`,`created_at`,`updated_at`) VALUES (34,1,29,NULL,NULL);
INSERT INTO `privileges` (`id`,`role_id`,`resource_id`,`created_at`,`updated_at`) VALUES (35,1,30,NULL,NULL);
INSERT INTO `privileges` (`id`,`role_id`,`resource_id`,`created_at`,`updated_at`) VALUES (36,1,31,NULL,NULL);
